name: Jekyll Bootstrap Blog
description: A blog theme for Jekyll using Twitter Bootstrap
author: Andrew Shell

# Please remove or change to your own from http://disqus.com/
disqus_shortname: jekyll-bootstrap-blog

navigation:
- text: Home
  url: /
  icon: "glyphicon glyphicon-home"
- text: About
  url: /about.html
- text: Layouts
  url: /layouts/
  children:
  - text: Default
    url: /layouts/default.html
  - text: Sidebar Left
    url: /layouts/sidebar-left.html
  - text: No Sidebar
    url: /layouts/no-sidebar.html

paginate: 10

# Scheme and Hostname for your website without trailing slash
# (ex: https://andrewshell.github.com)
url: http://www.jekyll-bootstrap-blog.com

# Folder part of the path to get to your website without trailing slash
# (ex: /projectname)
baseurl:

githuburl: https://github.com/andrewshell/jekyll-bootstrap-blog

safe: true
